source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'  
use_frameworks!  
target 'SwiftDemo' do   
	pod 'Alamofire', '~> 4.7'
	pod 'SwiftyJSON'
	pod 'SnapKit', '~> 4.0.0'
	pod 'SDWebImage', '~> 4.0'
	pod 'FSPagerView'
	pod 'HandyJSON', '~> 4.1.1'
end  
