source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!  
target 'SwiftDemo' do   
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SnapKit'
	pod 'SDWebImage'
	pod 'FSPagerView'
	pod 'HandyJSON'
end  
